import React from 'react';

const AboutPage = () => {
  return (
    <div className="about-container">
      <header className="about-header">
        <h1>About Science X Sci-Fi</h1>
      </header>
      
      <div className="about-content">
        <h2>Who are we?</h2>
        <p>
          Science X Sci-Fi (SXSF) is a project of <a href="https://research.monash.edu/en/persons/simon-angus">Prof Simon Angus</a> and <a href="https://research.monash.edu/en/persons/lachlan-oneill">Lachlan O'Neill</a> from <a href="https://sodalabs.io">SoDa Laboratories, Monash University</a> -- a research lab working at the intersection of AI, machine learning, computational science, economics and social science. Science X Sci-Fi started as a weekly email to a small group of friends and colleagues, including the corresponding authors of the papers that inspired these stories. The project has since grown into a public platform, with the goal of making science more engaging and accessible to everyone. 
        </p>

        <h2>Our Purpose</h2>
        <p>
           Science X Sci-Fi aims to bridge the gap between cutting-edge scientific research and public engagement through the power of storytelling. Each week, we publish a new science fiction story inspired by a recent scientific breakthrough, making complex scientific concepts accessible and exciting.
        </p>
        
        <h2>AI-Generated Content, Inspired by Real Science</h2>
        <p>
          All stories on this site are generated by artificial intelligence, specifically designed to transform scientific papers and breakthroughs into engaging narratives. Each story is crafted to be both scientifically grounded and creatively compelling, with references to the original research that inspired it.
        </p>
        <p>
          In fact, the stories of Science X Sci-Fi are the product of an agentic AI system within Assistant GPT, itself an ingeneous tool spearheaded by Lachlan in our lab. <a href="https://www.datacamp.com/blog/agentic-ai">Agentic AI</a> means that instead of a single AI model call, a lead AI model is provided with an ecosystem of tools and other models that it can use to accomplisht the task, often over many iterative steps. In this case, the lead AI model was given the task of researching the a given scientific breakthrough by reading the papers and releases about the breakthrough, together with finding related research and news articles. The system then undertakes a series of planning and reflection steps to come up with compelling story lines, characters, plots and endings, before generating a draft story for editing and final polishing. All of this happens in a fully autonomous manner.
        </p>
        <p>
            Each story typically takes around 5 to 10min of system processing time, with between 10 and 15 individual AI research, synthesis, drafting, editing, and polishing steps, often carried out in parallel, altogether, around 500 thousand to 1 million words are read or generated during this process. Typically, models from <a href="https://www.anthropic.com/">Anthropic</a>, <a href="https://gemini.google.com/">Google</a> and <a href="https://openai.com/">OpenAI</a> are all used in this process.
        </p>
        <p>
          Images for each story are then created using <a href="https://openai.com/index/dall-e-3/">OpenAI's DALL-E</a> image generation model.
        </p>
        
        <h2>For Educators</h2>
        <p>
          Teachers and educators are encouraged to use these stories as resources in their classrooms. The combination of engaging narratives and real scientific concepts makes these stories excellent tools for sparking interest in STEM subjects among students of all ages.
        </p>
        
        <h2>For Science Enthusiasts</h2>
        <p>
          If you're passionate about science but find academic papers challenging to digest, our stories offer an alternative way to stay informed about the latest discoveries. Each story includes links to the original research, allowing you to explore further if a particular topic captures your interest.
        </p>
        
        <h2>Weekly Updates</h2>
        <p>
          We publish a new story every week, each focusing on a different scientific breakthrough. Check back regularly to discover new stories and explore the fascinating intersection of science and imagination.
        </p>
        <h2>Contact</h2>
        <p>
          We'd love to hear from you, especially if you are using SXSF in a science educational way, or for any suggestions or comments. Please email Simon at <a href="mailto:simon.angus@monash.edu?subject=SXSF%20Contact">simon.angus@monash.edu</a>.
        </p>
      </div>
    </div>
  );
};

export default AboutPage;
