// This file is auto-generated by scripts/generate-story-index.js
// Do not edit it manually

export const storyFiles = [
  'corrections',
  'echo-patterns',
  'echoes-of-ancient-impact',
  'echoes-of-the-living',
  'the-quintessence-hunters'
];
